name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
    - uses: actions/checkout@v4
    - uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        target: ${{ matrix.target }}
        working-directory: xurdf-python
        args: --release -o dist --find-interpreter
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.run_id }}-${{ github.job }}-${{ matrix.target }}
        path: xurdf-python/dist

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: messense/maturin-action@v1
      with:
        command: build
        working-directory: xurdf-python
        args: --release -o dist --find-interpreter
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.run_id }}-${{ github.job }}
        path: xurdf-python/dist

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: messense/maturin-action@v1
      with:
        command: build
        working-directory: xurdf-python
        args: --release -o dist --universal2 --find-interpreter
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.run_id }}-${{ github.job }}
        path: xurdf-python/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ macos, windows, linux ]
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*